In [1]:
import numpy as np

***Завдання 1: Створення матриць та векторів***

In [2]:
vector = np.random.rand(10)
matrix = np.array([[11,14,17],
                  [20,23,26],
                  [29,32,35]])
print(f'Вектор та його розмір:\n{vector}\n{vector.shape}')
print(f'Матриця та її розмір:\n{matrix}\n{matrix.shape}')

Вектор та його розмір:
[0.65533435 0.72902448 0.65722423 0.04517897 0.87515672 0.86251852
 0.55165824 0.32315971 0.12188455 0.42813194]
(10,)
Матриця та її розмір:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
(3, 3)


***Завдання 2: Операції над векторами та матрицями***

In [3]:
vector_add = vector + 10
matrix_mult = matrix * 2
vector_sqrt = vector ** 2

print(f'Додавання вектора\n {np.array2string(vector_add, precision=2, suppress_small=True)}')
print(f'Множення матриці\n {matrix_mult}')
print(f'Вектор квардратів\n {vector_sqrt}')

Додавання вектора
 [10.66 10.73 10.66 10.05 10.88 10.86 10.55 10.32 10.12 10.43]
Множення матриці
 [[22 28 34]
 [40 46 52]
 [58 64 70]]
Вектор квардратів
 [0.42946312 0.5314767  0.43194369 0.00204114 0.76589929 0.7439382
 0.30432682 0.1044322  0.01485584 0.18329695]


***Завдання 3: Множення матриць***

In [5]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [6]:
C = np.array([[0], [1]])
result_matrix_C = np.dot(result_matrix, C)
result_matrix_C

array([[0.5202],
       [0.2846]])

In [7]:
D = np.array([[0,1], [1,0]])
result_matrix_D = np.dot(result_matrix, D)
result_matrix_D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

***Завдання 4: Транспонування матриць***

In [8]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [9]:
display(vector.T)
vector.T.shape

array([0.65533435, 0.72902448, 0.65722423, 0.04517897, 0.87515672,
       0.86251852, 0.55165824, 0.32315971, 0.12188455, 0.42813194])

(10,)

Зміни відсутні

In [10]:
column_vector = np.expand_dims(vector, axis=1)
display(column_vector)
column_vector.shape

array([[0.65533435],
       [0.72902448],
       [0.65722423],
       [0.04517897],
       [0.87515672],
       [0.86251852],
       [0.55165824],
       [0.32315971],
       [0.12188455],
       [0.42813194]])

(10, 1)

Дані представлені матрицею 10х1

In [11]:
display(column_vector.T)
column_vector.T.shape

array([[0.65533435, 0.72902448, 0.65722423, 0.04517897, 0.87515672,
        0.86251852, 0.55165824, 0.32315971, 0.12188455, 0.42813194]])

(1, 10)